# Generated by Django 2.2.12 on 2020-09-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plastic_tracker', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='id_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='monthly_balance',
            field=models.FloatField(default=2.0),
        ),
    ]
